
columns_to_drop = [ 
    "data.data",
    "tcp.payload",
    "http.file_data",
    "udp.payload",

    "http.connection",
    "http.content_length",
    "http.content_type",
    "http.date",
    "http.file_data",
    "http.host",
    "http.last_modified",
    "http.location",
    "http.next_request_in",
    "http.next_response_in",
    "http.request.full_uri",
    "http.request.line",
    "http.request.method",
    "http.request.uri.path",
    "http.request.uri.query",
    "http.request.uri.query.parameter",
    "http.request.version",
    "http.request_in",
    "http.response.code",
    "http.response.code.desc",
    "http.response.line",
    "http.response.phrase",
    "http.response.version",
    "http.response_for.uri",
    "http.response_in",
    "http.referer",
    "http.time",
    "http.server",
    "json.value.string",
    "json.key",

    "nbss.continuation_data",
    "dns.resp.name",

    "ssh.cookie",
    "ssh.compression_algorithms_client_to_server_length",
    "ssh.compression_algorithms_server_to_client_length",
    "ssh.direction",
    "ssh.dh_gex.max",
    "ssh.dh_gex.min",
    "ssh.dh_gex.nbits",
    "ssh.encryption_algorithms_client_to_server_length",
    "ssh.encryption_algorithms_server_to_client_length",
    "ssh.host_key.length",
    "ssh.host_key.type_length",
    "ssh.kex_algorithms_length",
    "ssh.mac_algorithms_client_to_server_length",
    "ssh.mac_algorithms_server_to_client_length",
    "ssh.message_code",
    "ssh.mpint_length",
    "ssh.packet_length",
    "ssh.packet_length_encrypted",
    "ssh.padding_length",
    "ssh.padding_string",
    "ssh.protocol",
    "ssh.server_host_key_algorithms_length",
]

columns_to_drop2 = [

    "radiotap.rxflags",
    "radiotap.vendor_oui",
    "wlan.analysis.kck",
    "wlan.analysis.kek",
    "wlan.country_info.fnm",
    "wlan.country_info.code",
    "wlan.fcs.bad_checksum",
    "wlan_radio.channel",
    "wlan_radio.frequency",
    "udp.dstport",
    "udp.srcport",
    "ldap",
    "smb.access.generic_execute",
    "smb.access.generic_read",
    "smb.access.generic_write",
    "smb.flags.notify",
    "smb.flags.response",
    "smb.flags2.nt_error",
    "smb.flags2.sec_sig",
    "smb.mid",
    "smb.nt_status",
    "smb.server_component",
    "smb.pid.high",
    "smb.tid",
    "smb2.acct",
    "smb2.auth_frame",
    "smb2.data_offset",
    "smb2.domain",
    "smb2.filename",
    "smb2.header_len",
    "smb2.host",
    "smb2.previous_sesid",
    "smb2.session_flags",
    "smb2.write_length",
    "dhcp",
    "dhcp.cookie",
    "dhcp.option.vendor.bsdp.message_type",
    "dns.resp.len",
    "tls.connection_id"
]

columns_to_drop3 = [
    "tcp.dstport",
    "dns.resp.ttl",
    "tls.record.version",
    "tcp.analysis.flags",
    "tls.handshake.version",
    "dhcp.ip.server",
    "dns.retransmit_request",
    "tcp.flags.reset",
    "tls.app_data_proto",
    "dns.count.queries",
    "dhcp.id",
    "llc",
    "tcp.analysis.retransmission",
    "tcp.flags.syn",
    "dns.count.auth_rr",
    "arp.dst.hw_mac",
    "dns",
    "mdns",
    "smb2.fid",
    "dns.qry.name",
    "ip.version",
    "ssdp",
    "dns.flags.response",
    "dns.flags.opcode",
    "arp.dst.proto_ipv4",
    "dns.count.add_rr",
    "tcp.analysis.rto_frame",
    "ip.src",
    "tls.record.content_type",
    "wlan.rsn.ie.pmkid",
    "wlan_rsna_eapol.keydes.nonce",
    "wlan_rsna_eapol.keydes.data_len",
    "wlan_rsna_eapol.keydes.msgnr",
    "wlan_rsna_eapol.keydes.key_info.key_mic",
    "wlan.rsn.capabilities.mfpc",
    "wlan.fixed.capabilities.ibss",
    "radiotap.channel.flags.ofdm",
    "radiotap.channel.flags.cck",
    "wlan.fixed.beacon",
    "radiotap.channel.freq",
    "wlan.fixed.capabilities.ess",
    "wlan.rsn.ie.igtk.key",
    "wlan.rsn.ie.gtk.key",
    "wlan.fixed.timestamp",
    "eapol.keydes.replay_counter",
    "eapol.keydes.key_len",
    "icmpv6.mldr.nb_mcast_records",
    "eapol.len",
    "smb2.tid",
    "dhcp.client_id.duid_ll_hw_type",
    "smb2.protocol_id",
    "smb2.sesid",
    "eapol.type",
    "dhcp.ip.client",
    "nbss.length",
    "smb2.cmd",
    "smb2.msg_id",
    "dhcp.hw.addr_padding",
    "dhcp.ip.relay",
    "nbns",
    "tls.alert_message.level",
    "tls.compress_certificate.compressed_certificate_message.length",
    "tls.alert_message.desc",
    "dns.retransmit_response",
    "dhcp.option.broadcast_address",
    "dhcp.option.dhcp_server_id",
    "dhcp.option.router",
    "dns.ptr.domain_name",
    "nbss.type",
    "smb2.pid",
    "frame.encap_type",
    "tcp.analysis.reused_ports",
    "arp.hw.type",
    "arp.proto.type",
    "arp.proto.size",
    "icmpv6.ni.nonce",
    "arp.hw.size",
    "arp.opcode",
    "tcp.analysis",
    "dns.count.labels",
    "ip.proto",
    "dns.flags.authoritative",
    "tcp.flags.fin",
    "dns.flags.checkdisable",
    "dhcp.hw.mac_addr",
    "dns.count.answers",
    "arp.src.hw_mac",
    "arp.src.proto_ipv4",
    "tcp.flags.ack",
    "dns.qry.name.len",
    "dns.resp.len.1",
    "tls.handshake.session_ticket_length",
    "dns.id",
    "smb2.buffer_code",
    "dns.a",
    "ip.ttl",
    "wlan_rsna_eapol.keydes.data",
    "tls.handshake.extensions_key_share_group",
    "tcp.flags.push",
    "tls.handshake.extension.type",
    "tcp.option_len",
    "ip.dst",
]

columns_to_drop4 = [
    
]

columns_to_drop_final = ['data.data', 'tcp.payload', 'http.file_data', 'udp.payload', 'http.connection', 'http.content_length', 'http.content_type', 'http.date', 'http.host', 'http.last_modified', 'http.location', 'http.next_request_in', 'http.next_response_in', 'http.request.full_uri', 'http.request.line', 'http.request.method', 'http.request.uri.path', 'http.request.uri.query', 'http.request.uri.query.parameter', 'http.request.version', 'http.request_in', 'http.response.code', 'http.response.code.desc', 'http.response.line', 'http.response.phrase', 'http.response.version', 'http.response_for.uri', 'http.response_in', 'http.referer', 'http.time', 'http.server', 'json.value.string', 'json.key', 'nbss.continuation_data', 'dns.resp.name', 'ssh.cookie', 'ssh.compression_algorithms_client_to_server_length', 'ssh.compression_algorithms_server_to_client_length', 'ssh.direction', 'ssh.dh_gex.max', 'ssh.dh_gex.min', 'ssh.dh_gex.nbits', 'ssh.encryption_algorithms_client_to_server_length', 'ssh.encryption_algorithms_server_to_client_length', 'ssh.host_key.length', 'ssh.host_key.type_length', 'ssh.kex_algorithms_length', 'ssh.mac_algorithms_client_to_server_length', 'ssh.mac_algorithms_server_to_client_length', 'ssh.message_code', 'ssh.mpint_length', 'ssh.packet_length', 'ssh.packet_length_encrypted', 'ssh.padding_length', 'ssh.padding_string', 'ssh.protocol', 'ssh.server_host_key_algorithms_length', 'radiotap.rxflags', 'radiotap.vendor_oui', 'wlan.analysis.kck', 'wlan.analysis.kek', 'wlan.country_info.fnm', 'wlan.country_info.code', 'wlan.fcs.bad_checksum', 'wlan_radio.channel', 'wlan_radio.frequency', 'udp.dstport', 'udp.srcport', 'ldap', 'smb.access.generic_execute', 'smb.access.generic_read', 'smb.access.generic_write', 'smb.flags.notify', 'smb.flags.response', 'smb.flags2.nt_error', 'smb.flags2.sec_sig', 'smb.mid', 'smb.nt_status', 'smb.server_component', 'smb.pid.high', 'smb.tid', 'smb2.acct', 'smb2.auth_frame', 'smb2.data_offset', 'smb2.domain', 'smb2.filename', 'smb2.header_len', 'smb2.host', 'smb2.previous_sesid', 'smb2.session_flags', 'smb2.write_length', 'dhcp', 'dhcp.cookie', 'dhcp.option.vendor.bsdp.message_type', 'dns.resp.len', 'tls.connection_id', 'tcp.dstport', 'dns.resp.ttl', 'tls.record.version', 'tcp.analysis.flags', 'tls.handshake.version', 'dhcp.ip.server', 'dns.retransmit_request', 'tcp.flags.reset', 'tls.app_data_proto', 'dns.count.queries', 'dhcp.id', 'llc', 'tcp.analysis.retransmission', 'tcp.flags.syn', 'dns.count.auth_rr', 'arp.dst.hw_mac', 'dns', 'mdns', 'smb2.fid', 'dns.qry.name', 'ip.version', 'ssdp', 'dns.flags.response', 'dns.flags.opcode', 'arp.dst.proto_ipv4', 'dns.count.add_rr', 'tcp.analysis.rto_frame', 'ip.src', 'tls.record.content_type', 'wlan.rsn.ie.pmkid', 'wlan_rsna_eapol.keydes.nonce', 'wlan_rsna_eapol.keydes.data_len', 'wlan_rsna_eapol.keydes.msgnr', 'wlan_rsna_eapol.keydes.key_info.key_mic', 'wlan.rsn.capabilities.mfpc', 'wlan.fixed.capabilities.ibss', 'radiotap.channel.flags.ofdm', 'radiotap.channel.flags.cck', 'wlan.fixed.beacon', 'radiotap.channel.freq', 'wlan.fixed.capabilities.ess', 'wlan.rsn.ie.igtk.key', 'wlan.rsn.ie.gtk.key', 'wlan.fixed.timestamp', 'eapol.keydes.replay_counter', 'eapol.keydes.key_len', 'icmpv6.mldr.nb_mcast_records', 'eapol.len', 'smb2.tid', 'dhcp.client_id.duid_ll_hw_type', 'smb2.protocol_id', 'smb2.sesid', 'eapol.type', 'dhcp.ip.client', 'nbss.length', 'smb2.cmd', 'smb2.msg_id', 'dhcp.hw.addr_padding', 'dhcp.ip.relay', 'nbns', 'tls.alert_message.level', 'tls.compress_certificate.compressed_certificate_message.length', 'tls.alert_message.desc', 'dns.retransmit_response', 'dhcp.option.broadcast_address', 'dhcp.option.dhcp_server_id', 'dhcp.option.router', 'dns.ptr.domain_name', 'nbss.type', 'smb2.pid', 'frame.encap_type', 'tcp.analysis.reused_ports', 'arp.hw.type', 'arp.proto.type', 'arp.proto.size', 'icmpv6.ni.nonce', 'arp.hw.size', 'arp.opcode', 'tcp.analysis', 'dns.count.labels', 'ip.proto', 'dns.flags.authoritative', 'tcp.flags.fin', 'dns.flags.checkdisable', 'dhcp.hw.mac_addr', 'dns.count.answers', 'arp.src.hw_mac', 'arp.src.proto_ipv4', 'tcp.flags.ack', 'dns.qry.name.len', 'dns.resp.len.1', 'tls.handshake.session_ticket_length', 'dns.id', 'smb2.buffer_code', 'dns.a', 'ip.ttl', 'wlan_rsna_eapol.keydes.data', 'tls.handshake.extensions_key_share_group', 'tcp.flags.push', 'tls.handshake.extension.type', 'tcp.option_len', 'ip.dst', 'wlan.tag']












dtypes={
    "frame.encap_type": "string",
    "frame.len": "string",
    "frame.number": "string",
    "frame.time": "string",
    "frame.time_delta": "string",
    "frame.time_delta_displayed": "string",
    "frame.time_epoch": "string",
    "frame.time_relative": "string",
    "radiotap.channel.flags.cck": "string",
    "radiotap.channel.flags.ofdm": "string",
    "radiotap.channel.freq": "string",
    "radiotap.datarate": "string",
    "radiotap.dbm_antsignal": "string",
    "radiotap.length": "string",
    "radiotap.mactime": "string",
    "radiotap.present.tsft": "string",
    "radiotap.rxflags": "string",
    "radiotap.timestamp.ts": "string",
    "radiotap.vendor_oui": "string",
    "wlan.duration": "string",
    "wlan.analysis.kck": "string",
    "wlan.analysis.kek": "string",
    "wlan.bssid": "string",
    "wlan.country_info.fnm": "string",
    "wlan.country_info.code": "string",
    "wlan.da": "string",
    "wlan.fc.ds": "string",
    "wlan.fc.frag": "string",
    "wlan.fc.order": "string",
    "wlan.fc.moredata": "string",
    "wlan.fc.protected": "string",
    "wlan.fc.pwrmgt": "string",
    "wlan.fc.type": "string",
    "wlan.fc.retry": "string",
    "wlan.fc.subtype": "string",
    "wlan.fcs.bad_checksum": "string",
    "wlan.fixed.beacon": "string",
    "wlan.fixed.capabilities.ess": "string",
    "wlan.fixed.capabilities.ibss": "string",
    "wlan.fixed.reason_code": "string",
    "wlan.fixed.timestamp": "string",
    "wlan.ra": "string",
    "wlan_radio.duration": "string",
    "wlan.rsn.ie.gtk.key": "string",
    "wlan.rsn.ie.igtk.key": "string",
    "wlan.rsn.ie.pmkid": "string",
    "wlan.sa": "string",
    "wlan.seq": "string",
    "wlan.ssid": "string",
    "wlan.ta": "string",
    "wlan.tag": "string",
    "wlan.tag.length": "string",
    "wlan_radio.channel": "string",
    "wlan_radio.data_rate": "string",
    "wlan_radio.end_tsf": "string",
    "wlan_radio.frequency": "string",
    "wlan_radio.signal_dbm": "string",
    "wlan_radio.start_tsf": "string",
    "wlan_radio.phy": "string",
    "wlan_radio.timestamp": "string",
    "wlan.rsn.capabilities.mfpc": "string",
    "wlan_rsna_eapol.keydes.msgnr": "string",
    "wlan_rsna_eapol.keydes.data": "string",
    "wlan_rsna_eapol.keydes.data_len": "string",
    "wlan_rsna_eapol.keydes.key_info.key_mic": "string",
    "wlan_rsna_eapol.keydes.nonce": "string",
    "eapol.keydes.key_len": "string",
    "eapol.keydes.replay_counter": "string",
    "eapol.len": "string",
    "eapol.type": "string",
    "llc": "string",
    "arp": "string",
    "arp.hw.type": "string",
    "arp.proto.type": "string",
    "arp.hw.size": "string",
    "arp.proto.size": "string",
    "arp.opcode": "string",
    "arp.src.hw_mac": "string",
    "arp.src.proto_ipv4": "string",
    "arp.dst.hw_mac": "string",
    "arp.dst.proto_ipv4": "string",
    "ip.dst": "string",
    "ip.proto": "string",
    "ip.src": "string",
    "ip.ttl": "string",
    "ip.version": "string",
    "data.data": "string",
    "data.len": "string",
    "icmpv6.mldr.nb_mcast_records": "string",
    "icmpv6.ni.nonce": "string",
    "tcp.ack": "string",
    "tcp.ack_raw": "string",
    "tcp.analysis": "string",
    "tcp.analysis.flags": "string",
    "tcp.analysis.retransmission": "string",
    "tcp.analysis.reused_ports": "string",
    "tcp.analysis.rto_frame": "string",
    "tcp.checksum": "string",
    "tcp.checksum.status": "string",
    "tcp.flags.syn": "string",
    "tcp.dstport": "string",
    "tcp.flags.ack": "string",
    "tcp.flags.fin": "string",
    "tcp.flags.push": "string",
    "tcp.flags.reset": "string",
    "tcp.option_len": "string",
    "tcp.payload": "string",
    "tcp.seq": "string",
    "tcp.seq_raw": "string",
    "tcp.srcport": "string",
    "tcp.time_delta": "string",
    "tcp.time_relative": "string",
    "udp.dstport": "string",
    "udp.srcport": "string",
    "udp.length": "string",
    "udp.payload": "string",
    "udp.time_relative": "string",
    "udp.time_delta": "string",
    "nbns": "string",
    "nbss.continuation_data": "string",
    "nbss.type": "string",
    "nbss.length": "string",
    "ldap": "string",
    "smb.access.generic_execute": "string",
    "smb.access.generic_read": "string",
    "smb.access.generic_write": "string",
    "smb.flags.notify": "string",
    "smb.flags.response": "string",
    "smb.flags2.nt_error": "string",
    "smb.flags2.sec_sig": "string",
    "smb.mid": "string",
    "smb.nt_status": "string",
    "smb.server_component": "string",
    "smb.pid.high": "string",
    "smb.tid": "string",
    "smb2.acct": "string",
    "smb2.auth_frame": "string",
    "smb2.buffer_code": "string",
    "smb2.cmd": "string",
    "smb2.data_offset": "string",
    "smb2.domain": "string",
    "smb2.fid": "string",
    "smb2.filename": "string",
    "smb2.header_len": "string",
    "smb2.host": "string",
    "smb2.msg_id": "string",
    "smb2.pid": "string",
    "smb2.previous_sesid": "string",
    "smb2.protocol_id": "string",
    "smb2.sesid": "string",
    "smb2.session_flags": "string",
    "smb2.tid": "string",
    "smb2.write_length": "string",
    "dhcp": "string",
    "dhcp.client_id.duid_ll_hw_type": "string",
    "dhcp.cookie": "string",
    "dhcp.hw.addr_padding": "string",
    "dhcp.hw.mac_addr": "string",
    "dhcp.id": "string",
    "dhcp.ip.client": "string",
    "dhcp.ip.relay": "string",
    "dhcp.ip.server": "string",
    "dhcp.option.broadcast_address": "string",
    "dhcp.option.dhcp_server_id": "string",
    "dhcp.option.router": "string",
    "dhcp.option.vendor.bsdp.message_type": "string",
    "mdns": "string",
    "dns": "string",
    "dns.a": "string",
    "dns.count.add_rr": "string",
    "dns.count.answers": "string",
    "dns.count.auth_rr": "string",
    "dns.count.labels": "string",
    "dns.count.queries": "string",
    "dns.flags.authoritative": "string",
    "dns.flags.checkdisable": "string",
    "dns.flags.opcode": "string",
    "dns.flags.response": "string",
    "dns.id": "string",
    "dns.ptr.domain_name": "string",
    "dns.qry.name": "string",
    "dns.qry.name.len": "string",
    "dns.resp.len": "string",
    "dns.resp.name": "string",
    "dns.resp.ttl": "string",
    "dns.resp.len.1": "string",
    "dns.retransmit_request": "string",
    "dns.retransmit_response": "string",
    "dns.time": "string",
    "ssdp": "string",
    "http.connection": "string",
    "http.content_length": "string",
    "http.content_type": "string",
    "http.date": "string",
    "http.file_data": "string",
    "http.host": "string",
    "http.last_modified": "string",
    "http.location": "string",
    "http.next_request_in": "string",
    "http.next_response_in": "string",
    "http.request.full_uri": "string",
    "http.request.line": "string",
    "http.request.method": "string",
    "http.request.uri.path": "string",
    "http.request.uri.query": "string",
    "http.request.uri.query.parameter": "string",
    "http.request.version": "string",
    "http.request_in": "string",
    "http.response.code": "string",
    "http.response.code.desc": "string",
    "http.response.line": "string",
    "http.response.phrase": "string",
    "http.response.version": "string",
    "http.response_for.uri": "string",
    "http.response_in": "string",
    "http.referer": "string",
    "http.time": "string",
    "http.server": "string",
    "json.value.string": "string",
    "json.key": "string",
    "ssh.cookie": "string",
    "ssh.compression_algorithms_client_to_server_length": "string",
    "ssh.compression_algorithms_server_to_client_length": "string",
    "ssh.direction": "string",
    "ssh.dh_gex.max": "string",
    "ssh.dh_gex.min": "string",
    "ssh.dh_gex.nbits": "string",
    "ssh.encryption_algorithms_client_to_server_length": "string",
    "ssh.encryption_algorithms_server_to_client_length": "string",
    "ssh.host_key.length": "string",
    "ssh.host_key.type_length": "string",
    "ssh.kex_algorithms_length": "string",
    "ssh.mac_algorithms_client_to_server_length": "string",
    "ssh.mac_algorithms_server_to_client_length": "string",
    "ssh.message_code": "string",
    "ssh.mpint_length": "string",
    "ssh.packet_length": "string",
    "ssh.packet_length_encrypted": "string",
    "ssh.padding_length": "string",
    "ssh.padding_string": "string",
    "ssh.protocol": "string",
    "ssh.server_host_key_algorithms_length": "string",
    "tls.alert_message.desc": "string",
    "tls.alert_message.level": "string",
    "tls.app_data_proto": "string",
    "tls.compress_certificate.compressed_certificate_message.length": "string",
    "tls.connection_id": "string",
    "tls.handshake.extension.type": "string",
    "tls.handshake.extensions_key_share_group": "string",
    "tls.handshake.session_ticket_length": "string",
    "tls.handshake.version": "string",
    "tls.record.content_type": "string",
    "tls.record.version": "string",
    "Label": "string",
}


dtypes_categorical = {
    "frame.encap_type": "string",
    "frame.len": "category",
    "frame.number": "string",
    "frame.time": "string",
    "frame.time_delta": "string",
    "frame.time_delta_displayed": "string",
    "frame.time_epoch": "string",
    "frame.time_relative": "string",
    "radiotap.channel.flags.cck": "string",
    "radiotap.channel.flags.ofdm": "string",
    "radiotap.channel.freq": "string",
    "radiotap.datarate": "category",
    "radiotap.dbm_antsignal": "string",
    "radiotap.length": "category",
    "radiotap.mactime": "string",
    "radiotap.present.tsft": "category",
    "radiotap.rxflags": "string",
    "radiotap.timestamp.ts": "string",
    "radiotap.vendor_oui": "string",
    "wlan.duration": "string",
    "wlan.analysis.kck": "string",
    "wlan.analysis.kek": "string",
    "wlan.bssid": "string",
    "wlan.country_info.fnm": "string",
    "wlan.country_info.code": "string",
    "wlan.da": "string",
    "wlan.fc.ds": "category",
    "wlan.fc.frag": "category",
    "wlan.fc.order": "category",
    "wlan.fc.moredata": "category",
    "wlan.fc.protected": "category",
    "wlan.fc.pwrmgt": "category",
    "wlan.fc.type": "category",
    "wlan.fc.retry": "string",
    "wlan.fc.subtype": "string",
    "wlan.fcs.bad_checksum": "string",
    "wlan.fixed.beacon": "string",
    "wlan.fixed.capabilities.ess": "string",
    "wlan.fixed.capabilities.ibss": "string",
    "wlan.fixed.reason_code": "string",
    "wlan.fixed.timestamp": "string",
    "wlan.ra": "string",
    "wlan_radio.duration": "string",
    "wlan.rsn.ie.gtk.key": "string",
    "wlan.rsn.ie.igtk.key": "string",
    "wlan.rsn.ie.pmkid": "string",
    "wlan.sa": "string",
    "wlan.seq": "string",
    "wlan.ssid": "category",
    "wlan.ta": "string",
    "wlan.tag": "string",
    "wlan.tag.length": "category",
    "wlan_radio.channel": "string",
    "wlan_radio.data_rate": "category",
    "wlan_radio.end_tsf": "string",
    "wlan_radio.frequency": "string",
    "wlan_radio.signal_dbm": "string",
    "wlan_radio.start_tsf": "string",
    "wlan_radio.phy": "category",
    "wlan_radio.timestamp": "string",
    "wlan.rsn.capabilities.mfpc": "string",
    "wlan_rsna_eapol.keydes.msgnr": "string",
    "wlan_rsna_eapol.keydes.data": "string",
    "wlan_rsna_eapol.keydes.data_len": "string",
    "wlan_rsna_eapol.keydes.key_info.key_mic": "string",
    "wlan_rsna_eapol.keydes.nonce": "string",
    "eapol.keydes.key_len": "string",
    "eapol.keydes.replay_counter": "string",
    "eapol.len": "string",
    "eapol.type": "string",
    "llc": "string",
    "arp": "category",
    "arp.hw.type": "string",
    "arp.proto.type": "string",
    "arp.hw.size": "string",
    "arp.proto.size": "string",
    "arp.opcode": "string",
    "arp.src.hw_mac": "string",
    "arp.src.proto_ipv4": "string",
    "arp.dst.hw_mac": "string",
    "arp.dst.proto_ipv4": "string",
    "ip.dst": "string",
    "ip.proto": "string",
    "ip.src": "string",
    "ip.ttl": "string",
    "ip.version": "string",
    "data.data": "string",
    "data.len": "category",
    "icmpv6.mldr.nb_mcast_records": "string",
    "icmpv6.ni.nonce": "string",
    "tcp.ack": "category",
    "tcp.ack_raw": "category",
    "tcp.analysis": "string",
    "tcp.analysis.flags": "string",
    "tcp.analysis.retransmission": "string",
    "tcp.analysis.reused_ports": "string",
    "tcp.analysis.rto_frame": "string",
    "tcp.checksum": "category",
    "tcp.checksum.status": "category",
    "tcp.flags.syn": "string",
    "tcp.dstport": "string",
    "tcp.flags.ack": "string",
    "tcp.flags.fin": "string",
    "tcp.flags.push": "string",
    "tcp.flags.reset": "string",
    "tcp.option_len": "string",
    "tcp.payload": "string",
    "tcp.seq": "category",
    "tcp.seq_raw": "category",
    "tcp.srcport": "category",
    "tcp.time_delta": "category",
    "tcp.time_relative": "category",
    "udp.dstport": "string",
    "udp.srcport": "string",
    "udp.length": "category",
    "udp.payload": "string",
    "udp.time_relative": "category",
    "udp.time_delta": "category",
    "nbns": "string",
    "nbss.continuation_data": "string",
    "nbss.type": "string",
    "nbss.length": "string",
    "ldap": "string",
    "smb.access.generic_execute": "string",
    "smb.access.generic_read": "string",
    "smb.access.generic_write": "string",
    "smb.flags.notify": "string",
    "smb.flags.response": "string",
    "smb.flags2.nt_error": "string",
    "smb.flags2.sec_sig": "string",
    "smb.mid": "string",
    "smb.nt_status": "string",
    "smb.server_component": "string",
    "smb.pid.high": "string",
    "smb.tid": "string",
    "smb2.acct": "string",
    "smb2.auth_frame": "string",
    "smb2.buffer_code": "string",
    "smb2.cmd": "string",
    "smb2.data_offset": "string",
    "smb2.domain": "string",
    "smb2.fid": "string",
    "smb2.filename": "string",
    "smb2.header_len": "string",
    "smb2.host": "string",
    "smb2.msg_id": "string",
    "smb2.pid": "string",
    "smb2.previous_sesid": "string",
    "smb2.protocol_id": "string",
    "smb2.sesid": "string",
    "smb2.session_flags": "string",
    "smb2.tid": "string",
    "smb2.write_length": "string",
    "dhcp": "string",
    "dhcp.client_id.duid_ll_hw_type": "string",
    "dhcp.cookie": "string",
    "dhcp.hw.addr_padding": "string",
    "dhcp.hw.mac_addr": "string",
    "dhcp.id": "string",
    "dhcp.ip.client": "string",
    "dhcp.ip.relay": "string",
    "dhcp.ip.server": "string",
    "dhcp.option.broadcast_address": "string",
    "dhcp.option.dhcp_server_id": "string",
    "dhcp.option.router": "string",
    "dhcp.option.vendor.bsdp.message_type": "string",
    "mdns": "string",
    "dns": "string",
    "dns.a": "string",
    "dns.count.add_rr": "string",
    "dns.count.answers": "string",
    "dns.count.auth_rr": "string",
    "dns.count.labels": "string",
    "dns.count.queries": "string",
    "dns.flags.authoritative": "string",
    "dns.flags.checkdisable": "string",
    "dns.flags.opcode": "string",
    "dns.flags.response": "string",
    "dns.id": "string",
    "dns.ptr.domain_name": "string",
    "dns.qry.name": "string",
    "dns.qry.name.len": "string",
    "dns.resp.len": "string",
    "dns.resp.name": "string",
    "dns.resp.ttl": "string",
    "dns.resp.len.1": "string",
    "dns.retransmit_request": "string",
    "dns.retransmit_response": "string",
    "dns.time": "category",
    "ssdp": "string",
    "http.connection": "string",
    "http.content_length": "string",
    "http.content_type": "string",
    "http.date": "string",
    "http.file_data": "string",
    "http.host": "string",
    "http.last_modified": "string",
    "http.location": "string",
    "http.next_request_in": "string",
    "http.next_response_in": "string",
    "http.request.full_uri": "string",
    "http.request.line": "string",
    "http.request.method": "string",
    "http.request.uri.path": "string",
    "http.request.uri.query": "string",
    "http.request.uri.query.parameter": "string",
    "http.request.version": "string",
    "http.request_in": "string",
    "http.response.code": "string",
    "http.response.code.desc": "string",
    "http.response.line": "string",
    "http.response.phrase": "string",
    "http.response.version": "string",
    "http.response_for.uri": "string",
    "http.response_in": "string",
    "http.referer": "string",
    "http.time": "string",
    "http.server": "string",
    "json.value.string": "string",
    "json.key": "string",
    "ssh.cookie": "string",
    "ssh.compression_algorithms_client_to_server_length": "string",
    "ssh.compression_algorithms_server_to_client_length": "string",
    "ssh.direction": "string",
    "ssh.dh_gex.max": "string",
    "ssh.dh_gex.min": "string",
    "ssh.dh_gex.nbits": "string",
    "ssh.encryption_algorithms_client_to_server_length": "string",
    "ssh.encryption_algorithms_server_to_client_length": "string",
    "ssh.host_key.length": "string",
    "ssh.host_key.type_length": "string",
    "ssh.kex_algorithms_length": "string",
    "ssh.mac_algorithms_client_to_server_length": "string",
    "ssh.mac_algorithms_server_to_client_length": "string",
    "ssh.message_code": "string",
    "ssh.mpint_length": "string",
    "ssh.packet_length": "string",
    "ssh.packet_length_encrypted": "string",
    "ssh.padding_length": "string",
    "ssh.padding_string": "string",
    "ssh.protocol": "string",
    "ssh.server_host_key_algorithms_length": "string",
    "tls.alert_message.desc": "string",
    "tls.alert_message.level": "string",
    "tls.app_data_proto": "string",
    "tls.compress_certificate.compressed_certificate_message.length": "string",
    "tls.connection_id": "string",
    "tls.handshake.extension.type": "string",
    "tls.handshake.extensions_key_share_group": "string",
    "tls.handshake.session_ticket_length": "string",
    "tls.handshake.version": "string",
    "tls.record.content_type": "string",
    "tls.record.version": "string",
    "Label": "category",
}


dtypes_final = {
    "frame.len": "float",
    "frame.time_delta": "float",
    "frame.time_delta_displayed": "float",
    "frame.time_epoch": "float",
    "frame.time_relative": "float",
    "radiotap.datarate": "float",
    "radiotap.dbm_antsignal": "float",
    "radiotap.length": "float",
    "radiotap.mactime": "float",
    "radiotap.present.tsft": "float",
    "radiotap.timestamp.ts": "float",
    "wlan.duration": "float",
    "wlan.fc.ds": "float",
    "wlan.fc.frag": "float",
    "wlan.fc.order": "float",
    "wlan.fc.moredata": "float",
    "wlan.fc.protected": "float",
    "wlan.fc.pwrmgt": "float",
    "wlan.fc.type": "float",
    "wlan.fc.retry": "float",
    "wlan.fc.subtype": "float",
    "wlan_radio.duration": "float",
    "wlan.ssid": "float",
    "wlan.tag.length": "float",
    "wlan_radio.data_rate": "float",
    "wlan_radio.end_tsf": "float",
    "wlan_radio.signal_dbm": "float",
    "wlan_radio.start_tsf": "float",
    "wlan_radio.phy": "float",
    "wlan_radio.timestamp": "float",
    "arp": "float",
    "data.len": "float",
    "tcp.ack": "float",
    "tcp.ack_raw": "float",
    "tcp.checksum": "float",
    "tcp.checksum.status": "float",
    "tcp.seq": "float",
    "tcp.seq_raw": "float",
    "tcp.srcport": "float",
    "tcp.time_delta": "float",
    "tcp.time_relative": "float",
    "udp.length": "float",
    "udp.time_relative": "float",
    "udp.time_delta": "float",
    "dns.time": "float",
    "Label": "string"
}


